version: 2.1

executors:
  go:
    docker:
      - image: circleci/golang:1.12

commands:
  test:
    steps:
      - run:
          name: Run test
          command: go test ./parser

jobs:
  build:
    working_directory: /go/src/github.com/sthtnr/monkey
    executor: go
    steps:
      - checkout
      - test
